### PR TITLE
Moved images and demos to separate folders, cleaned up examples, updated documentation.

### PR DESCRIPTION
**Pull request by torsteinnh**
I updated the latex templates to suit my own workflow a bit better, feel free to merge if it is useful for you.
The underlying goal is to make it more usable in overleaf, now the whole folder can be zipped and uploaded when creating a new slide without cluttering up the workspace too much.
It would be ideal if the .sty files could be moved to a subfolder as well, but I didn't have time to figure that out as of now.

### CODE REVIEW

**Comment by kellertuer** [comment]
Thanks for the ideas!

For the demos that looks good, for the other parts – one original idea (probably even before I took over) was to have all In one folder without subfolders so it is “move these files around and it works”.
And for sure that is a tradeoff between cluttering and non-working-after-copying (because one forgot to adapt folders).

So even for the images this might be dangerous, I have to try. I personally have that installed in my LaTeX path anyways and do never copy it around, which is the more advanced version – I am usually just too lazy to explain that for example for Windows users, where I always have to check where the LaTeX path is.
So, I will have to check for the images being in a subfolder, but the demos is a good idea, since they are just used in the docs, and there we can make sure that works.

**Comment by torsteinnh** [comment]
Thank you for the quick reply, let me know if the image part don't work, and I'll revert that part on my branch.

**Comment by kellertuer** [comment]
I will check, I think there was some good reason we did not move those – folder indication on windows, something like that, I have to find time to check.

**Comment by kellertuer** [comment]
I checked, and I do not feel 100% safe with moving the images;
moving the example PDFs is fine since they are included in the anyways pre-rendered docs, but the images might act different on different systems, so I would prefer to provide them in the same folder as the presentation main file.

Besides that we originally had a “start in English” and “start in Norwegian” example. Any reason why you unified that to one example, that is just the English one?

**Comment by torsteinnh** [comment]
I see, I moved the images back out now.

The main reason for merging the examples was to avoid mistakes where forget to delete the unused ones and start working on both. This recently happened to me with a shared overleaf project, and I had to manually merge the documents together.

**Comment by kellertuer** [comment]
Well, on the other hand, a person not so experienced with LaTeX and options in loading themes, but not find the right option to switch the language. That was the reason to provide 2 examples.

**Comment by torsteinnh** [comment]
I agree, that's why I included comments with the specific options to change. I think that, as long as the package is not in ctan, it is necessary to make some tradeoffs to aid overleaf-based workflows and assume some users will zip and upload the whole project as a template.

**Comment by kellertuer** [comment]
also on overleaf two examples to start would be fine

A CTAN package has several disadvantages here: The example would not be included there, then we would even need 2 repositories? Submitting to CTAN is not a very nice experience, tried that once. Prefer to not try that again.

**Comment by torsteinnh** [comment]
I am closing this since I'll develop my master branch in a different direction, this state is preserved in my ntnu-tex_compatible branch.

**Pull request closed without merging**
