### PR TITLE
Introduce a beamertheme using style files

### PR DESCRIPTION
**Pull request by kellertuer**
This PR introduces the theme with separate style files (inner, outer, color) following Chapter 15 of the LaTeX beamer manual http://tug.ctan.org/macros/latex/contrib/beamer/doc/beameruserguide.pdf

Further I introduced some theme options to set the language of the logo and activate/deactivate the total number of frames (had that lying round anyways). I tried to stick close to what was given in the original theme for the rest.

This way we could also introduce the other 3 themes, where I do not like the original circle one (and do not have the graphics for now).

Let me know what you think.

### CODE REVIEW

**Comment by kellertuer** [comment]
I just had a little bit of sub-theming fun. The original PPT files provide 4 styles, I was too lazy for the circles style 
  
kellertuer commented now
I had a little LaTeX Beamer fun today, so my PR now also covers (see documentation in the previous post) three styles (was too lazy to build the circles style for now), but there is now the option `\usetheme[style=...] with

* `plain` https://github.com/kellertuer/beamerthementnu/blob/master/beamerntnu2020/ntnu-beamer-example_plain.pdf
* `stripe` https://github.com/kellertuer/beamerthementnu/blob/master/beamerntnu2020/ntnu-beamer-example_stripe.pdf
* `stripebottom` https://github.com/kellertuer/beamerthementnu/blob/master/beamerntnu2020/ntnu-beamer-example_stripebottom.pdf

and one can switch the slogan using the option `slogan=norsk` to the Norwegian slogan/logo/name.
This is also documented in https://github.com/kellertuer/beamerthementnu/blob/master/beamerntnu2020/ntnu-beamer-documentation.pdf

**Comment by martstr** [comment]
Mattia is now the maintainer of this (I left NTNU three years ago), and I won't have any opinion on his decisions, but it could be useful to compare your syntax to that of the [earlier version](https://github.com/martstr/beamerthementnu/tree/f51e546c5181360be55d6057716de16cc5190498/beamerthementnu2017) to maintain backwards compatibility to that.

**Comment by kellertuer** [comment]
Thanks for the feedback, I was not aware of the previous versions – and for sure not about the current repository structure; I am just own at NTNU and your repository was linked in the wiki.

Would it maybe be reasonable to move this repository to some organisation where it is easier to maintain the main developer(s)?

Compared to that earlier version (interesting, that there was once a style file based variant and that kind of got lost), I am not using the expl3-Syntax, but for sure one could adopt the style names (horizontal, vertical, simple).

**Comment by martstr** [comment]
I'm by no means clinging on to it (rather the opposite ...), so feel free to talk to @VeroniMattia to figure out a good solution.

**Comment by VeroniMattia** [comment]
Dear all, thank you for your questions and suggestions. When I was asked to create a new template that resembled the new NTNU style, I was also asked to do it in a way that requires minimal knowledge of tex, that was easy to deploy and modify. We then agreed upon a stand-alone file instead of a style-based approach.
That said, I'm very happy and grateful to hear that someone is willing to contribute, and feels like adding a style file would be beneficial. First of all, thanks for your precious contribution. We can discuss this further via email ( mattia.veroni(at)ntnu(dot)no ). 
I must admit that I have very little time in the coming weeks, but I will be able to work on it myself starting from June.

**Review by VeroniMattia — APPROVED** [review]

**Review by VeroniMattia — APPROVED** [review]

**Review by VeroniMattia — APPROVED** [review]

**Comment by kellertuer** [comment]
Hi,
thanks for the fast response.
May I ask, what the benefit of the single file is, when one has to copy the images anyways? Then one can also copy the style files.
My aim here is to maybe also include a good starters tutorial (as slides) that document both a) how to get startet and b) what the options of the theme are. The second part is already in the documentation slides. For the first part I might have the problem, that I am working already quite long with both TeX and Beamer, so I might be too fast for beginners for sure. But an idea of slides to part (a) would be, that a user has to have not much knowledge. Something along the lines of
1) Copy images and sty files to a folder
2) start your presentation by typing the content in example_pres.tex.

The advances user would for sure install said files in her/hin LaTeX path then.

And don't worry, we are for sure not I a hurry, with the current version of this PR I have a theme that I can build my slides on, so thanks for the start and let's see where we can get these slides to :)

**Pull request merged**
